-- Top up the language taxonomy with all the values that were in the
-- original hardcoded list in wave-cms-portal/frontend/components/releases/wizard-tracks.tsx
-- so nothing is lost when the CMS switches to sa_taxonomies as the source of truth.

INSERT INTO public.sa_taxonomies (type, value, label, sort_order) VALUES
  ('language', 'afrikaans',   'Afrikaans',   300),
  ('language', 'amharic',     'Amharic',     310),
  ('language', 'assamese',    'Assamese',    320),
  ('language', 'bhojpuri',    'Bhojpuri',    330),
  ('language', 'burmese',     'Burmese',     340),
  ('language', 'catalan',     'Catalan',     350),
  ('language', 'czech',       'Czech',       360),
  ('language', 'danish',      'Danish',      370),
  ('language', 'dogri',       'Dogri',       380),
  ('language', 'dutch',       'Dutch',       390),
  ('language', 'filipino',    'Filipino (Tagalog)', 400),
  ('language', 'finnish',     'Finnish',     410),
  ('language', 'greek',       'Greek',       420),
  ('language', 'hausa',       'Hausa',       430),
  ('language', 'hebrew',      'Hebrew',      440),
  ('language', 'igbo',        'Igbo',        450),
  ('language', 'indonesian',  'Indonesian',  460),
  ('language', 'kashmiri',    'Kashmiri',    470),
  ('language', 'khmer',       'Khmer',       480),
  ('language', 'konkani',     'Konkani',     490),
  ('language', 'maithili',    'Maithili',    500),
  ('language', 'malay',       'Malay',       510),
  ('language', 'manipuri',    'Manipuri',    520),
  ('language', 'nepali',      'Nepali',      530),
  ('language', 'norwegian',   'Norwegian',   540),
  ('language', 'odia',        'Odia',        550),
  ('language', 'persian',     'Persian (Farsi)', 560),
  ('language', 'polish',      'Polish',      570),
  ('language', 'romanian',    'Romanian',    580),
  ('language', 'sanskrit',    'Sanskrit',    590),
  ('language', 'sindhi',      'Sindhi',      600),
  ('language', 'sinhala',     'Sinhala',     610),
  ('language', 'somali',      'Somali',      620),
  ('language', 'swahili',     'Swahili',     630),
  ('language', 'swedish',     'Swedish',     640),
  ('language', 'thai',        'Thai',        650),
  ('language', 'turkish',     'Turkish',     660),
  ('language', 'vietnamese',  'Vietnamese',  670),
  ('language', 'yoruba',      'Yoruba',      680),
  ('language', 'zulu',        'Zulu',        690)
ON CONFLICT (type, value) DO NOTHING;
